package com.equifax.course.model.domain;
// Generated Mar 20, 2020, 10:36:34 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Courses generated by hbm2java
 */
@Entity
@Table(name = "Courses", catalog = "equifax")
public class Course implements Serializable
{
	private static final long serialVersionUID = 1L;

	private Integer idCourse;
	private String code;
	private String name;
//	private List<Student> students = new ArrayList<>();

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_course", unique = true, nullable = false)
	public Integer getId()
	{
		return this.idCourse;
	}

	public void setId(Integer idCourse)
	{
		this.idCourse = idCourse;
	}

	@Column(name = "code", nullable = false, length = 4)
	public String getCode()
	{
		return this.code;
	}

	public void setCode(String code)
	{
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
//	public List<Student> getStudents()
//	{
//		return this.students;
//	}
//
//	public void setStudents(List<Student> students)
//	{
//		this.students = students;
//	}
}
