package com.equifax.course.model.domain;
// Generated Mar 23, 2020, 12:39:21 AM by Hibernate Tools 5.2.12.Final

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "Roles", catalog = "equifax")
public class Role implements Serializable
{
	private static final long serialVersionUID = 1L;

	private Integer idRole;
	private String name;
	private List<UserRole> usersRole = new ArrayList<UserRole>();

	@Id
	@Column(name = "id_role", unique = true, nullable = false)
	public Integer getId()
	{
		return this.idRole;
	}

	public void setId(Integer idRole)
	{
		this.idRole = idRole;
	}

	@Column(name = "name", unique = true, nullable = false, length = 16)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public List<UserRole> getUsersRole()
	{
		return this.usersRole;
	}

	public void setUsersRole(List<UserRole> usersRole)
	{
		this.usersRole = usersRole;
	}
}
