package com.equifax.course.model.domain;
// Generated Mar 20, 2020, 10:36:34 PM by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Students generated by hbm2java
 */
@Entity
@Table(name = "Students", catalog = "equifax")
public class Student implements Serializable
{
	private static final long serialVersionUID = 1L;

	private Integer idStudent;
	private Course course;
	private String rut;
	private String name;
	private String lastName;
	private Byte age;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_student", unique = true, nullable = false)
	public Integer getId()
	{
		return this.idStudent;
	}

	public void setId(Integer idStudent)
	{
		this.idStudent = idStudent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public Course getCourse()
	{
		return this.course;
	}

	public void setCourse(Course course)
	{
		this.course = course;
	}

	@Column(name = "rut", unique = true, nullable = false, length = 11)
	public String getRut()
	{
		return this.rut;
	}

	public void setRut(String rut)
	{
		this.rut = rut;
	}

	@Column(name = "name", nullable = false, length = 32)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "last_name", nullable = false, length = 32)
	public String getLastName()
	{
		return this.lastName;
	}

	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	@Column(name = "age", nullable = false)
	public Byte getAge()
	{
		return this.age;
	}

	public void setAge(Byte age)
	{
		this.age = age;
	}
}
