package com.equifax.course.model.domain;
// Generated Mar 23, 2020, 12:39:21 AM by Hibernate Tools 5.2.12.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersRolesId generated by hbm2java
 */
@Embeddable
public class UserRoleId implements Serializable
{
	private static final long serialVersionUID = 1L;

	private int userId;
	private int roleId;

	@Column(name = "user_id", nullable = false)
	public int getUserId()
	{
		return this.userId;
	}

	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId()
	{
		return this.roleId;
	}

	public void setRoleId(int roleId)
	{
		this.roleId = roleId;
	}

	public boolean equals(Object other)
	{
		if ((this == other)) return true;
		if ((other == null)) return false;
		if (!(other instanceof UserRoleId)) return false;
		UserRoleId castOther = (UserRoleId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getRoleId() == castOther.getRoleId());
	}

	public int hashCode()
	{
		int result = 17;
		result = 37 * result + this.getUserId();
		result = 37 * result + this.getRoleId();
		return result;
	}
}
